replicas:
  _default: 1
  dev: 1

selector : dev

name:
  app: car-helm

service:
  nameApp: car-helm-service
  portName: helm-car
  type: NodePort
  port: 80
  targetPort: 8001

kafka:
  portName: port-delivery-kafka
  type: NodePort
  port: 9092
  targetPort: 9092
  bootstrap: kafka:9092

image:
  repository: bobah165/carservice
  tag: v5

ingress:
  enabled: false
  name: "car-service-helm-ingress"
  className: nginx
  host: "arch.homework"
  pathType: Prefix
  path: /

db:
  url: jdbc:postgresql://my-db-postgresql:5432/postgres

app:
  db:
    password:
      _default: cG9zdGdyZXM=
    username:
      _default: cG9zdGdyZXM=

